spring.application.name=cios-content-service
server.port=7002

management.endpoints.web.exposure.include=health

#-------------------- PostgreSQL configuration--------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/sunbird
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.main.allow-bean-definition-overriding=true

#-------------------------tranformation-------------------------------------
transformation.source-to-target.spec.path=/Transformation/cornell.json
cornell.progress.transformation.source-to-target.spec.path=/Transformation/cornellProgressJson.json

#------------------------Kafka Configuration---------------------------------
#kafka Server
spring.kafka.bootstrap.servers=localhost:9092
spring.kafka.cornell.topic.name=dev.enrollment.progress
spring.kafka.consumer.group.id=enrollment-progress
#kafka properties
kakfa.offset.reset.value=latest
kafka.max.poll.interval.ms=15000
kafka.max.poll.records=100
kafka.auto.commit.interval.ms=10000

#--------------------Redis config-----------------------------------------------
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.cacheTtl= 86400
search.result.redis.ttl=600

#-----------Cassandra Configuration-----------------
spring.data.cassandra.startupTimeoutInSeconds=100000
spring.data.cassandra.contact-points=localhost
spring.data.cassandra.port=9042
spring.data.cassandra.keyspace-name=sunbird
spring.data.cassandra.username=sunbird
spring.data.cassandra.password=""
spring.data.cassandra.local-datacenter=DC1
cassandra.config.host=localhost

#---------------Service registry configuration--------------
service.locator.host=http://localhost:8096
service.locator.fixedurl=/serviceregistry/api/v1/callExternalApi

#---------------cornell configuration----------------
cornell.enrollment.service.code=cornell-enrollment-list
scheduler.enabled=true
scheduler.fixedRate=600000
scheduler.cron=0 13 17 * * *
cornell.enrollment.list.limit=10
cornell.enrollment.list.course_type=lesson
cornell.date.range=7

#-------------------cb-pores partnerService---------------------------------------------
cb.pores.service.url=http://localhost:7001
partner.read.path=/contentpartner/v1/readbypartnercode/
partner.create.update.path=/contentpartner/v1/create
cios.read.api.fixed.url=/cios/v1/content/readby/externalid/

#--------------ElasticSearch configuration--------------------
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.username=
elasticsearch.password=
elastic.required.field.cios.content.json.path=/EsFieldsMapping/esRequiredFieldsJsonFilePath.json


#-----------------Partner Code Configurations--------------------
cornell.partner.code=CORNELL
upgrad.partner.code=UPGRAD
coursera.partner.code=COURSERA

#-------------------Cloud Storage Service properties------------------------
cloud.storage.type.name=gcloud
cloud.storage.key=kb-gcr-repo-access-prj-kb-nprd@prj-kb-nprd-dev-gcp-1004.iam.gserviceaccount.com
cloud.storage.secret=-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQAH/lXJ+9GFTo\n8N2SaEbeSs4coFBelPMA8wNVC3wG62qUFZ/ghHQ6rLBsERQexBqNeAYoX7HZqfoD\n+OFRwWw9x7wRE6oU1GbeOOQGmh3k9QMlv8TcziaZLu4hipfvEGY5davQBcuuTBGb\nSNxYI2FAK9XjblJJJo+bJHGFp45rLTJoVfo3QFjHIM9P+vhH8/02mpmcQ9RqUNOn\nTRnGJuCoGEmZFIf7sW9w4qGp12xstIhn++Vkg5cETh+G3mQ4OdrtTsdkwF/HNc9J\nRw4Ea66mBAcu8w6fe1M9dc0k/kjbN+/zQQ84crGnOJcbry3Y8/wQwGnQOEv04pmO\nHsmtjwmFAgMBAAECggEAKgbb0KJPJUQoDdvzDPy0SwBm1lpe+slSMzAmzXVxVS2W\nXn7jC5h/qoZPbDpkLBY3/jsQ1XIGa6IgQdK05hG0luQHQBUO0cAb2803Z40Wurb1\nsJgnhOzDWEKm+1B3Q+a2nOgFc9Xj8l7s1MkbOlTFttNUl2woRJ79t51csaJqEIXW\n2YkQdQF5SElQVg9dP00iRorRsgnECPO4AvoKb5niMfdT8JyipzrEkVgROBa0YJ0O\nkUwTv9WUxMMw2FxhdlJQsVF1f/9CWMfNC+6avakP1dHm/tOPBMvdz9vP6N5hX7LK\niJbLrsnATFQC+asoQkDJMxB+BN4Bl647lk78cmkCwQKBgQD+8jp2JcoLVTUbSh4F\noKcl6AK4JPkpFE0VCYKxTlxt/0DdcBEkRMnE01vTdZducPqZRmWrhvmO6k6KvQ2S\nsRDiKD+AZkRqt+uqnv8u/apWVnHquAz8iXNtnwMOFWg6oZnwFfNDo27eiFemdyTh\nx8fc7TjQvdLyLsuj7qYhbcvLQQKBgQDQ3JjcNbtVl/TElrXMQCSGnkHOeWoJCuvQ\n7i9gEeacK4GttY5tAuYau9QABspWlslGqI0Tbb2tXboMegZfrFnZgFBtcWmjO6Bj\n4P6VArCEDvJAfJdXQbrh9yx2LDoW8VBujAl2i5E7lDkE6OELdqT8gIzv370ZIYhH\nPYesglYBRQKBgQC7jc3OXyyNO8kO427EqxRsQYvGloSqYOH4KP/5mnFLBq5ceXZS\n3TwmTWtPXEHkIL9rBSwEjQ6Iwfy3+i7DDPojtoJI3nNUoyt/YOrQUhL+4yd5Cp+b\nJS9CpOllcgA0qfAKfMtypggJM/pvX1VFuGhjMi1K+2r1edGcLxQOoax8QQKBgQCE\n1zm2Hcq3xv1cKAsbDNTudiueumRxueuAqG2jad9GBvnk1SvwM77M1BgjqC37Ys5D\nzaJk8BCK+qkBlH8HTOSczNrasR6iPqNlw03I0rwYUjVMRLIxQlIttHsn8jtEKlmg\n5hqCtoQ5461cbQ3tr5mCK/T4AFMSb9xwizcGxqMTDQKBgHqj9J5oxV3Ylj3/PQex\nrV+99PrkAH7l7bU3r59IZtYBGbud/z39AjoJLxQLNc1Xd5S/AqH0Jk/9Yni4RK1F\no/HYRPfH4vjPctiQJ0xtgpF0BldzwgYa4hnBn3bw4b7OuABtGw+756gfEwZ95+6p\nVMHPdgKPnK/Kq6rOIITdzVsX\n-----END PRIVATE KEY-----
cloud.container.name=sb-cb-ext
cloud.profile.image.container.name=igot
cloud.storage.endpoint=https://storage.googleapis.com

cios.cloud.container.name=cb-cios-dev
cios.logs.cloud.folder.name=cios-logs

kafka.topic.content.onboarding=cios.content.onboard
content.onboarding.consumer.group=cios.content.onboard.group
